#
# This file contains configuration flags to customize your site
#

# Name of your site
name: Ahmed Badawi
author: Ahmed Badawi
title: ChainReaction
email: ahmedabadawi@gmail.com
github_username: ahmedabadawi
linkedin_username: ahmedabadawi
flickr_username: ahmedabadawi

# Short bio or description
description: Thoughts and Notes in Software Development

# URL of your avatar or profile pic
avatar: https://avatars3.githubusercontent.com/u/1433946?s=320

disqus: disqus_ahmedabadawi
google_analytics: UA-118873516-1

# Your website URL
url: https://ahmedabadawi.github.io/blog

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

plugins:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

markdown: kramdown
theme: jekyll-theme-hacker

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: ahmedabadawi@gmail.com
  facebook: aabadawi
  flickr: ahmedabadawi
  github: ahmedabadawi
  linkedin: ahmedabadawi
  twitter: ahmedabadawi
  stackoverflow: users/story/5650786


